dubbo:
  application:
    name: gmall-cart-web
  consumer:
    timeout: 120000
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: cn.com.gmall.cart.controller
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper

spring:
  thymeleaf:
    cache: false
