dubbo:
  application:
    name: gmall-item-web
  consumer:
    timeout: 1200000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.com.gmall.item.controller
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper

# 跨域配置
cross-origin:
  address: http://127.0.0.1:8888

spring:
  thymeleaf:
    cache: false
