dubbo:
  application:
    name: gmall-user-web
  consumer:
    timeout: 3000
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: cn.com.gmall.user.controller
  registry:
    address: zookeeper://192.168.133.129:2181
    check: false
    protocol: zookeeper


jedis-util:
  host: 192.168.133.129
  port: 6379
  password:
  time-out: 10000
  max-wait-millis: 10000
  max-idle: 5
  max-total: 3
  test-on-return: true
  test-on-borrow: true
  test-while-idle: true
  block-when-exhausted: true